trigger:
- main

pool: gent1

steps:
- script: |
    echo "Setting JAVA_HOME to the installed JDK"
    echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
    echo "##vso[task.prependpath]$(JAVA_HOME)/bin"
  displayName: 'Set JAVA_HOME variable and update PATH'

- script: |
    echo "Java version:"
    java --version
  displayName: 'Check Java version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
