trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '86e12c8d-35a1-4b95-b1ec-7dec2302f36d'

  # Web app name
  webAppName: 'revhiredevops'

  # Environment name
  environmentName: 'revhiredevops'

  # Agent pool name
  agentPoolName: 'gent1'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: $(agentPoolName)

    steps:
    - script: |
        echo "Setting JAVA_HOME to the installed JDK"
        echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
        echo "##vso[task.prependpath]$(JAVA_HOME)/bin"
      displayName: 'Set JAVA_HOME variable and update PATH'

    - script: |
        echo "Java version:"
        java --version
      displayName: 'Check Java version'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'Path'
        jdkDirectory: '$(JAVA_HOME)'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/target'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Artifact'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      name: $(agentPoolName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/*.jar'

#update              
              
